#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudyOnline_Nuong
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="StudyEnglishOnline_Nuong")]
	public partial class StudyOnlineDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBAIHOC(BAIHOC instance);
    partial void UpdateBAIHOC(BAIHOC instance);
    partial void DeleteBAIHOC(BAIHOC instance);
    partial void InsertTRINHDO(TRINHDO instance);
    partial void UpdateTRINHDO(TRINHDO instance);
    partial void DeleteTRINHDO(TRINHDO instance);
    partial void InsertCAUHOI(CAUHOI instance);
    partial void UpdateCAUHOI(CAUHOI instance);
    partial void DeleteCAUHOI(CAUHOI instance);
    partial void InsertCHUYENMUC(CHUYENMUC instance);
    partial void UpdateCHUYENMUC(CHUYENMUC instance);
    partial void DeleteCHUYENMUC(CHUYENMUC instance);
    partial void InsertKHOAHOC(KHOAHOC instance);
    partial void UpdateKHOAHOC(KHOAHOC instance);
    partial void DeleteKHOAHOC(KHOAHOC instance);
    partial void InsertPHANHOC(PHANHOC instance);
    partial void UpdatePHANHOC(PHANHOC instance);
    partial void DeletePHANHOC(PHANHOC instance);
    partial void InsertPHANHOI(PHANHOI instance);
    partial void UpdatePHANHOI(PHANHOI instance);
    partial void DeletePHANHOI(PHANHOI instance);
    partial void InsertTHANHVIEN(THANHVIEN instance);
    partial void UpdateTHANHVIEN(THANHVIEN instance);
    partial void DeleteTHANHVIEN(THANHVIEN instance);
    partial void InsertTHANHVIEN_KHOAHOC(THANHVIEN_KHOAHOC instance);
    partial void UpdateTHANHVIEN_KHOAHOC(THANHVIEN_KHOAHOC instance);
    partial void DeleteTHANHVIEN_KHOAHOC(THANHVIEN_KHOAHOC instance);
    #endregion
		
		public StudyOnlineDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["StudyEnglishOnline_NuongConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StudyOnlineDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudyOnlineDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudyOnlineDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StudyOnlineDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<BAIHOC> BAIHOCs
		{
			get
			{
				return this.GetTable<BAIHOC>();
			}
		}
		
		public System.Data.Linq.Table<TRINHDO> TRINHDOs
		{
			get
			{
				return this.GetTable<TRINHDO>();
			}
		}
		
		public System.Data.Linq.Table<CAUHOI> CAUHOIs
		{
			get
			{
				return this.GetTable<CAUHOI>();
			}
		}
		
		public System.Data.Linq.Table<CHUYENMUC> CHUYENMUCs
		{
			get
			{
				return this.GetTable<CHUYENMUC>();
			}
		}
		
		public System.Data.Linq.Table<KHOAHOC> KHOAHOCs
		{
			get
			{
				return this.GetTable<KHOAHOC>();
			}
		}
		
		public System.Data.Linq.Table<PHANHOC> PHANHOCs
		{
			get
			{
				return this.GetTable<PHANHOC>();
			}
		}
		
		public System.Data.Linq.Table<PHANHOI> PHANHOIs
		{
			get
			{
				return this.GetTable<PHANHOI>();
			}
		}
		
		public System.Data.Linq.Table<THANHVIEN> THANHVIENs
		{
			get
			{
				return this.GetTable<THANHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<THANHVIEN_KHOAHOC> THANHVIEN_KHOAHOCs
		{
			get
			{
				return this.GetTable<THANHVIEN_KHOAHOC>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAIHOC")]
	public partial class BAIHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaBaiHoc;
		
		private string _TenBaiHoc;
		
		private string _LoaiNoiDung;
		
		private string _NoiDungBaiHoc;
		
		private System.Nullable<int> _ThuTu;
		
		private System.Nullable<int> _MaPhanHoc;
		
		private EntityRef<PHANHOC> _PHANHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaiHocChanging(int value);
    partial void OnMaBaiHocChanged();
    partial void OnTenBaiHocChanging(string value);
    partial void OnTenBaiHocChanged();
    partial void OnLoaiNoiDungChanging(string value);
    partial void OnLoaiNoiDungChanged();
    partial void OnNoiDungBaiHocChanging(string value);
    partial void OnNoiDungBaiHocChanged();
    partial void OnThuTuChanging(System.Nullable<int> value);
    partial void OnThuTuChanged();
    partial void OnMaPhanHocChanging(System.Nullable<int> value);
    partial void OnMaPhanHocChanged();
    #endregion
		
		public BAIHOC()
		{
			this._PHANHOC = default(EntityRef<PHANHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaBaiHoc
		{
			get
			{
				return this._MaBaiHoc;
			}
			set
			{
				if ((this._MaBaiHoc != value))
				{
					this.OnMaBaiHocChanging(value);
					this.SendPropertyChanging();
					this._MaBaiHoc = value;
					this.SendPropertyChanged("MaBaiHoc");
					this.OnMaBaiHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenBaiHoc", DbType="NVarChar(250)")]
		public string TenBaiHoc
		{
			get
			{
				return this._TenBaiHoc;
			}
			set
			{
				if ((this._TenBaiHoc != value))
				{
					this.OnTenBaiHocChanging(value);
					this.SendPropertyChanging();
					this._TenBaiHoc = value;
					this.SendPropertyChanged("TenBaiHoc");
					this.OnTenBaiHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiNoiDung", DbType="Char(50)")]
		public string LoaiNoiDung
		{
			get
			{
				return this._LoaiNoiDung;
			}
			set
			{
				if ((this._LoaiNoiDung != value))
				{
					this.OnLoaiNoiDungChanging(value);
					this.SendPropertyChanging();
					this._LoaiNoiDung = value;
					this.SendPropertyChanged("LoaiNoiDung");
					this.OnLoaiNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungBaiHoc", DbType="NVarChar(MAX)")]
		public string NoiDungBaiHoc
		{
			get
			{
				return this._NoiDungBaiHoc;
			}
			set
			{
				if ((this._NoiDungBaiHoc != value))
				{
					this.OnNoiDungBaiHocChanging(value);
					this.SendPropertyChanging();
					this._NoiDungBaiHoc = value;
					this.SendPropertyChanged("NoiDungBaiHoc");
					this.OnNoiDungBaiHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanHoc", DbType="Int")]
		public System.Nullable<int> MaPhanHoc
		{
			get
			{
				return this._MaPhanHoc;
			}
			set
			{
				if ((this._MaPhanHoc != value))
				{
					if (this._PHANHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhanHocChanging(value);
					this.SendPropertyChanging();
					this._MaPhanHoc = value;
					this.SendPropertyChanged("MaPhanHoc");
					this.OnMaPhanHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANHOC_BAIHOC", Storage="_PHANHOC", ThisKey="MaPhanHoc", OtherKey="MaPhanHoc", IsForeignKey=true)]
		public PHANHOC PHANHOC
		{
			get
			{
				return this._PHANHOC.Entity;
			}
			set
			{
				PHANHOC previousValue = this._PHANHOC.Entity;
				if (((previousValue != value) 
							|| (this._PHANHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHANHOC.Entity = null;
						previousValue.BAIHOCs.Remove(this);
					}
					this._PHANHOC.Entity = value;
					if ((value != null))
					{
						value.BAIHOCs.Add(this);
						this._MaPhanHoc = value.MaPhanHoc;
					}
					else
					{
						this._MaPhanHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHANHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRINHDO")]
	public partial class TRINHDO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaTrinhDo;
		
		private string _TenTrinhDo;
		
		private System.Nullable<bool> _TrangThai;
		
		private string _GhiChu;
		
		private EntitySet<KHOAHOC> _KHOAHOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaTrinhDoChanging(int value);
    partial void OnMaTrinhDoChanged();
    partial void OnTenTrinhDoChanging(string value);
    partial void OnTenTrinhDoChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public TRINHDO()
		{
			this._KHOAHOCs = new EntitySet<KHOAHOC>(new Action<KHOAHOC>(this.attach_KHOAHOCs), new Action<KHOAHOC>(this.detach_KHOAHOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrinhDo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaTrinhDo
		{
			get
			{
				return this._MaTrinhDo;
			}
			set
			{
				if ((this._MaTrinhDo != value))
				{
					this.OnMaTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._MaTrinhDo = value;
					this.SendPropertyChanged("MaTrinhDo");
					this.OnMaTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenTrinhDo", DbType="NVarChar(250)")]
		public string TenTrinhDo
		{
			get
			{
				return this._TenTrinhDo;
			}
			set
			{
				if ((this._TenTrinhDo != value))
				{
					this.OnTenTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._TenTrinhDo = value;
					this.SendPropertyChanged("TenTrinhDo");
					this.OnTenTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(250)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRINHDO_KHOAHOC", Storage="_KHOAHOCs", ThisKey="MaTrinhDo", OtherKey="MaTrinhDo")]
		public EntitySet<KHOAHOC> KHOAHOCs
		{
			get
			{
				return this._KHOAHOCs;
			}
			set
			{
				this._KHOAHOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHOAHOCs(KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.TRINHDO = this;
		}
		
		private void detach_KHOAHOCs(KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.TRINHDO = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CAUHOI")]
	public partial class CAUHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaCauHoi;
		
		private string _TenCauHoi;
		
		private System.Nullable<int> _MaPhanHoc;
		
		private string _NoiDungCauHoi;
		
		private string _DapAnA;
		
		private string _DapAnB;
		
		private string _DapAnC;
		
		private string _DapAnD;
		
		private string _DapAnDung;
		
		private string _LoaiCauHoi;
		
		private EntityRef<PHANHOC> _PHANHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaCauHoiChanging(int value);
    partial void OnMaCauHoiChanged();
    partial void OnTenCauHoiChanging(string value);
    partial void OnTenCauHoiChanged();
    partial void OnMaPhanHocChanging(System.Nullable<int> value);
    partial void OnMaPhanHocChanged();
    partial void OnNoiDungCauHoiChanging(string value);
    partial void OnNoiDungCauHoiChanged();
    partial void OnDapAnAChanging(string value);
    partial void OnDapAnAChanged();
    partial void OnDapAnBChanging(string value);
    partial void OnDapAnBChanged();
    partial void OnDapAnCChanging(string value);
    partial void OnDapAnCChanged();
    partial void OnDapAnDChanging(string value);
    partial void OnDapAnDChanged();
    partial void OnDapAnDungChanging(string value);
    partial void OnDapAnDungChanged();
    partial void OnLoaiCauHoiChanging(string value);
    partial void OnLoaiCauHoiChanged();
    #endregion
		
		public CAUHOI()
		{
			this._PHANHOC = default(EntityRef<PHANHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaCauHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaCauHoi
		{
			get
			{
				return this._MaCauHoi;
			}
			set
			{
				if ((this._MaCauHoi != value))
				{
					this.OnMaCauHoiChanging(value);
					this.SendPropertyChanging();
					this._MaCauHoi = value;
					this.SendPropertyChanged("MaCauHoi");
					this.OnMaCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenCauHoi", DbType="NVarChar(250)")]
		public string TenCauHoi
		{
			get
			{
				return this._TenCauHoi;
			}
			set
			{
				if ((this._TenCauHoi != value))
				{
					this.OnTenCauHoiChanging(value);
					this.SendPropertyChanging();
					this._TenCauHoi = value;
					this.SendPropertyChanged("TenCauHoi");
					this.OnTenCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanHoc", DbType="Int")]
		public System.Nullable<int> MaPhanHoc
		{
			get
			{
				return this._MaPhanHoc;
			}
			set
			{
				if ((this._MaPhanHoc != value))
				{
					if (this._PHANHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaPhanHocChanging(value);
					this.SendPropertyChanging();
					this._MaPhanHoc = value;
					this.SendPropertyChanged("MaPhanHoc");
					this.OnMaPhanHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungCauHoi", DbType="NVarChar(500)")]
		public string NoiDungCauHoi
		{
			get
			{
				return this._NoiDungCauHoi;
			}
			set
			{
				if ((this._NoiDungCauHoi != value))
				{
					this.OnNoiDungCauHoiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungCauHoi = value;
					this.SendPropertyChanged("NoiDungCauHoi");
					this.OnNoiDungCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnA", DbType="NVarChar(250)")]
		public string DapAnA
		{
			get
			{
				return this._DapAnA;
			}
			set
			{
				if ((this._DapAnA != value))
				{
					this.OnDapAnAChanging(value);
					this.SendPropertyChanging();
					this._DapAnA = value;
					this.SendPropertyChanged("DapAnA");
					this.OnDapAnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnB", DbType="NVarChar(250)")]
		public string DapAnB
		{
			get
			{
				return this._DapAnB;
			}
			set
			{
				if ((this._DapAnB != value))
				{
					this.OnDapAnBChanging(value);
					this.SendPropertyChanging();
					this._DapAnB = value;
					this.SendPropertyChanged("DapAnB");
					this.OnDapAnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnC", DbType="NVarChar(250)")]
		public string DapAnC
		{
			get
			{
				return this._DapAnC;
			}
			set
			{
				if ((this._DapAnC != value))
				{
					this.OnDapAnCChanging(value);
					this.SendPropertyChanging();
					this._DapAnC = value;
					this.SendPropertyChanged("DapAnC");
					this.OnDapAnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnD", DbType="NVarChar(250)")]
		public string DapAnD
		{
			get
			{
				return this._DapAnD;
			}
			set
			{
				if ((this._DapAnD != value))
				{
					this.OnDapAnDChanging(value);
					this.SendPropertyChanging();
					this._DapAnD = value;
					this.SendPropertyChanged("DapAnD");
					this.OnDapAnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DapAnDung", DbType="Char(10)")]
		public string DapAnDung
		{
			get
			{
				return this._DapAnDung;
			}
			set
			{
				if ((this._DapAnDung != value))
				{
					this.OnDapAnDungChanging(value);
					this.SendPropertyChanging();
					this._DapAnDung = value;
					this.SendPropertyChanged("DapAnDung");
					this.OnDapAnDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiCauHoi", DbType="NChar(10)")]
		public string LoaiCauHoi
		{
			get
			{
				return this._LoaiCauHoi;
			}
			set
			{
				if ((this._LoaiCauHoi != value))
				{
					this.OnLoaiCauHoiChanging(value);
					this.SendPropertyChanging();
					this._LoaiCauHoi = value;
					this.SendPropertyChanged("LoaiCauHoi");
					this.OnLoaiCauHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANHOC_CAUHOI", Storage="_PHANHOC", ThisKey="MaPhanHoc", OtherKey="MaPhanHoc", IsForeignKey=true)]
		public PHANHOC PHANHOC
		{
			get
			{
				return this._PHANHOC.Entity;
			}
			set
			{
				PHANHOC previousValue = this._PHANHOC.Entity;
				if (((previousValue != value) 
							|| (this._PHANHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHANHOC.Entity = null;
						previousValue.CAUHOIs.Remove(this);
					}
					this._PHANHOC.Entity = value;
					if ((value != null))
					{
						value.CAUHOIs.Add(this);
						this._MaPhanHoc = value.MaPhanHoc;
					}
					else
					{
						this._MaPhanHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("PHANHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHUYENMUC")]
	public partial class CHUYENMUC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaChuyenMuc;
		
		private string _TenChuyenMuc;
		
		private System.Nullable<int> _MaChuyenMucCha;
		
		private string _LoaiChuyenMuc;
		
		private string _Link;
		
		private System.Nullable<int> _ThuTu;
		
		private System.Nullable<bool> _TrangThai;
		
		private string _GhiChu;
		
		private EntitySet<KHOAHOC> _KHOAHOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaChuyenMucChanging(int value);
    partial void OnMaChuyenMucChanged();
    partial void OnTenChuyenMucChanging(string value);
    partial void OnTenChuyenMucChanged();
    partial void OnMaChuyenMucChaChanging(System.Nullable<int> value);
    partial void OnMaChuyenMucChaChanged();
    partial void OnLoaiChuyenMucChanging(string value);
    partial void OnLoaiChuyenMucChanged();
    partial void OnLinkChanging(string value);
    partial void OnLinkChanged();
    partial void OnThuTuChanging(System.Nullable<int> value);
    partial void OnThuTuChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public CHUYENMUC()
		{
			this._KHOAHOCs = new EntitySet<KHOAHOC>(new Action<KHOAHOC>(this.attach_KHOAHOCs), new Action<KHOAHOC>(this.detach_KHOAHOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenMuc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaChuyenMuc
		{
			get
			{
				return this._MaChuyenMuc;
			}
			set
			{
				if ((this._MaChuyenMuc != value))
				{
					this.OnMaChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenMuc = value;
					this.SendPropertyChanged("MaChuyenMuc");
					this.OnMaChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenChuyenMuc", DbType="NVarChar(250)")]
		public string TenChuyenMuc
		{
			get
			{
				return this._TenChuyenMuc;
			}
			set
			{
				if ((this._TenChuyenMuc != value))
				{
					this.OnTenChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._TenChuyenMuc = value;
					this.SendPropertyChanged("TenChuyenMuc");
					this.OnTenChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenMucCha", DbType="Int")]
		public System.Nullable<int> MaChuyenMucCha
		{
			get
			{
				return this._MaChuyenMucCha;
			}
			set
			{
				if ((this._MaChuyenMucCha != value))
				{
					this.OnMaChuyenMucChaChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenMucCha = value;
					this.SendPropertyChanged("MaChuyenMucCha");
					this.OnMaChuyenMucChaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoaiChuyenMuc", DbType="Char(50)")]
		public string LoaiChuyenMuc
		{
			get
			{
				return this._LoaiChuyenMuc;
			}
			set
			{
				if ((this._LoaiChuyenMuc != value))
				{
					this.OnLoaiChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._LoaiChuyenMuc = value;
					this.SendPropertyChanged("LoaiChuyenMuc");
					this.OnLoaiChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Link", DbType="NVarChar(500)")]
		public string Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				if ((this._Link != value))
				{
					this.OnLinkChanging(value);
					this.SendPropertyChanging();
					this._Link = value;
					this.SendPropertyChanged("Link");
					this.OnLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ThuTu", DbType="Int")]
		public System.Nullable<int> ThuTu
		{
			get
			{
				return this._ThuTu;
			}
			set
			{
				if ((this._ThuTu != value))
				{
					this.OnThuTuChanging(value);
					this.SendPropertyChanging();
					this._ThuTu = value;
					this.SendPropertyChanged("ThuTu");
					this.OnThuTuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(250)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENMUC_KHOAHOC", Storage="_KHOAHOCs", ThisKey="MaChuyenMuc", OtherKey="MaChuyenMuc")]
		public EntitySet<KHOAHOC> KHOAHOCs
		{
			get
			{
				return this._KHOAHOCs;
			}
			set
			{
				this._KHOAHOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHOAHOCs(KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENMUC = this;
		}
		
		private void detach_KHOAHOCs(KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.CHUYENMUC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHOAHOC")]
	public partial class KHOAHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaKhoaHoc;
		
		private string _TenKhoaHoc;
		
		private string _AnhDaiDien;
		
		private string _VideoGioiThieu;
		
		private string _MoTa;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<int> _LuotXem;
		
		private System.Nullable<int> _SoHocVien;
		
		private System.Nullable<bool> _TrangThai;
		
		private System.Nullable<int> _MaChuyenMuc;
		
		private System.Nullable<int> _MaTrinhDo;
		
		private System.Nullable<double> _Gia;
		
		private EntitySet<PHANHOC> _PHANHOCs;
		
		private EntitySet<PHANHOI> _PHANHOIs;
		
		private EntitySet<THANHVIEN_KHOAHOC> _THANHVIEN_KHOAHOCs;
		
		private EntityRef<CHUYENMUC> _CHUYENMUC;
		
		private EntityRef<TRINHDO> _TRINHDO;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKhoaHocChanging(int value);
    partial void OnMaKhoaHocChanged();
    partial void OnTenKhoaHocChanging(string value);
    partial void OnTenKhoaHocChanged();
    partial void OnAnhDaiDienChanging(string value);
    partial void OnAnhDaiDienChanged();
    partial void OnVideoGioiThieuChanging(string value);
    partial void OnVideoGioiThieuChanged();
    partial void OnMoTaChanging(string value);
    partial void OnMoTaChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnLuotXemChanging(System.Nullable<int> value);
    partial void OnLuotXemChanged();
    partial void OnSoHocVienChanging(System.Nullable<int> value);
    partial void OnSoHocVienChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnMaChuyenMucChanging(System.Nullable<int> value);
    partial void OnMaChuyenMucChanged();
    partial void OnMaTrinhDoChanging(System.Nullable<int> value);
    partial void OnMaTrinhDoChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    #endregion
		
		public KHOAHOC()
		{
			this._PHANHOCs = new EntitySet<PHANHOC>(new Action<PHANHOC>(this.attach_PHANHOCs), new Action<PHANHOC>(this.detach_PHANHOCs));
			this._PHANHOIs = new EntitySet<PHANHOI>(new Action<PHANHOI>(this.attach_PHANHOIs), new Action<PHANHOI>(this.detach_PHANHOIs));
			this._THANHVIEN_KHOAHOCs = new EntitySet<THANHVIEN_KHOAHOC>(new Action<THANHVIEN_KHOAHOC>(this.attach_THANHVIEN_KHOAHOCs), new Action<THANHVIEN_KHOAHOC>(this.detach_THANHVIEN_KHOAHOCs));
			this._CHUYENMUC = default(EntityRef<CHUYENMUC>);
			this._TRINHDO = default(EntityRef<TRINHDO>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKhoaHoc", DbType="NVarChar(250)")]
		public string TenKhoaHoc
		{
			get
			{
				return this._TenKhoaHoc;
			}
			set
			{
				if ((this._TenKhoaHoc != value))
				{
					this.OnTenKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._TenKhoaHoc = value;
					this.SendPropertyChanged("TenKhoaHoc");
					this.OnTenKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhDaiDien", DbType="NVarChar(500)")]
		public string AnhDaiDien
		{
			get
			{
				return this._AnhDaiDien;
			}
			set
			{
				if ((this._AnhDaiDien != value))
				{
					this.OnAnhDaiDienChanging(value);
					this.SendPropertyChanging();
					this._AnhDaiDien = value;
					this.SendPropertyChanged("AnhDaiDien");
					this.OnAnhDaiDienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VideoGioiThieu", DbType="NVarChar(500)")]
		public string VideoGioiThieu
		{
			get
			{
				return this._VideoGioiThieu;
			}
			set
			{
				if ((this._VideoGioiThieu != value))
				{
					this.OnVideoGioiThieuChanging(value);
					this.SendPropertyChanging();
					this._VideoGioiThieu = value;
					this.SendPropertyChanged("VideoGioiThieu");
					this.OnVideoGioiThieuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoTa", DbType="NVarChar(500)")]
		public string MoTa
		{
			get
			{
				return this._MoTa;
			}
			set
			{
				if ((this._MoTa != value))
				{
					this.OnMoTaChanging(value);
					this.SendPropertyChanging();
					this._MoTa = value;
					this.SendPropertyChanged("MoTa");
					this.OnMoTaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LuotXem", DbType="Int")]
		public System.Nullable<int> LuotXem
		{
			get
			{
				return this._LuotXem;
			}
			set
			{
				if ((this._LuotXem != value))
				{
					this.OnLuotXemChanging(value);
					this.SendPropertyChanging();
					this._LuotXem = value;
					this.SendPropertyChanged("LuotXem");
					this.OnLuotXemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHocVien", DbType="Int")]
		public System.Nullable<int> SoHocVien
		{
			get
			{
				return this._SoHocVien;
			}
			set
			{
				if ((this._SoHocVien != value))
				{
					this.OnSoHocVienChanging(value);
					this.SendPropertyChanging();
					this._SoHocVien = value;
					this.SendPropertyChanged("SoHocVien");
					this.OnSoHocVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaChuyenMuc", DbType="Int")]
		public System.Nullable<int> MaChuyenMuc
		{
			get
			{
				return this._MaChuyenMuc;
			}
			set
			{
				if ((this._MaChuyenMuc != value))
				{
					if (this._CHUYENMUC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaChuyenMucChanging(value);
					this.SendPropertyChanging();
					this._MaChuyenMuc = value;
					this.SendPropertyChanged("MaChuyenMuc");
					this.OnMaChuyenMucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaTrinhDo", DbType="Int")]
		public System.Nullable<int> MaTrinhDo
		{
			get
			{
				return this._MaTrinhDo;
			}
			set
			{
				if ((this._MaTrinhDo != value))
				{
					if (this._TRINHDO.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaTrinhDoChanging(value);
					this.SendPropertyChanging();
					this._MaTrinhDo = value;
					this.SendPropertyChanged("MaTrinhDo");
					this.OnMaTrinhDoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOAHOC_PHANHOC", Storage="_PHANHOCs", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc")]
		public EntitySet<PHANHOC> PHANHOCs
		{
			get
			{
				return this._PHANHOCs;
			}
			set
			{
				this._PHANHOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOAHOC_PHANHOI", Storage="_PHANHOIs", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc")]
		public EntitySet<PHANHOI> PHANHOIs
		{
			get
			{
				return this._PHANHOIs;
			}
			set
			{
				this._PHANHOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOAHOC_THANHVIEN_KHOAHOC", Storage="_THANHVIEN_KHOAHOCs", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc")]
		public EntitySet<THANHVIEN_KHOAHOC> THANHVIEN_KHOAHOCs
		{
			get
			{
				return this._THANHVIEN_KHOAHOCs;
			}
			set
			{
				this._THANHVIEN_KHOAHOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CHUYENMUC_KHOAHOC", Storage="_CHUYENMUC", ThisKey="MaChuyenMuc", OtherKey="MaChuyenMuc", IsForeignKey=true)]
		public CHUYENMUC CHUYENMUC
		{
			get
			{
				return this._CHUYENMUC.Entity;
			}
			set
			{
				CHUYENMUC previousValue = this._CHUYENMUC.Entity;
				if (((previousValue != value) 
							|| (this._CHUYENMUC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CHUYENMUC.Entity = null;
						previousValue.KHOAHOCs.Remove(this);
					}
					this._CHUYENMUC.Entity = value;
					if ((value != null))
					{
						value.KHOAHOCs.Add(this);
						this._MaChuyenMuc = value.MaChuyenMuc;
					}
					else
					{
						this._MaChuyenMuc = default(Nullable<int>);
					}
					this.SendPropertyChanged("CHUYENMUC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRINHDO_KHOAHOC", Storage="_TRINHDO", ThisKey="MaTrinhDo", OtherKey="MaTrinhDo", IsForeignKey=true)]
		public TRINHDO TRINHDO
		{
			get
			{
				return this._TRINHDO.Entity;
			}
			set
			{
				TRINHDO previousValue = this._TRINHDO.Entity;
				if (((previousValue != value) 
							|| (this._TRINHDO.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRINHDO.Entity = null;
						previousValue.KHOAHOCs.Remove(this);
					}
					this._TRINHDO.Entity = value;
					if ((value != null))
					{
						value.KHOAHOCs.Add(this);
						this._MaTrinhDo = value.MaTrinhDo;
					}
					else
					{
						this._MaTrinhDo = default(Nullable<int>);
					}
					this.SendPropertyChanged("TRINHDO");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANHOCs(PHANHOC entity)
		{
			this.SendPropertyChanging();
			entity.KHOAHOC = this;
		}
		
		private void detach_PHANHOCs(PHANHOC entity)
		{
			this.SendPropertyChanging();
			entity.KHOAHOC = null;
		}
		
		private void attach_PHANHOIs(PHANHOI entity)
		{
			this.SendPropertyChanging();
			entity.KHOAHOC = this;
		}
		
		private void detach_PHANHOIs(PHANHOI entity)
		{
			this.SendPropertyChanging();
			entity.KHOAHOC = null;
		}
		
		private void attach_THANHVIEN_KHOAHOCs(THANHVIEN_KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.KHOAHOC = this;
		}
		
		private void detach_THANHVIEN_KHOAHOCs(THANHVIEN_KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.KHOAHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANHOC")]
	public partial class PHANHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhanHoc;
		
		private string _TenPhanHoc;
		
		private System.Nullable<int> _MaKhoaHoc;
		
		private EntitySet<BAIHOC> _BAIHOCs;
		
		private EntitySet<CAUHOI> _CAUHOIs;
		
		private EntityRef<KHOAHOC> _KHOAHOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhanHocChanging(int value);
    partial void OnMaPhanHocChanged();
    partial void OnTenPhanHocChanging(string value);
    partial void OnTenPhanHocChanged();
    partial void OnMaKhoaHocChanging(System.Nullable<int> value);
    partial void OnMaKhoaHocChanged();
    #endregion
		
		public PHANHOC()
		{
			this._BAIHOCs = new EntitySet<BAIHOC>(new Action<BAIHOC>(this.attach_BAIHOCs), new Action<BAIHOC>(this.detach_BAIHOCs));
			this._CAUHOIs = new EntitySet<CAUHOI>(new Action<CAUHOI>(this.attach_CAUHOIs), new Action<CAUHOI>(this.detach_CAUHOIs));
			this._KHOAHOC = default(EntityRef<KHOAHOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanHoc", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhanHoc
		{
			get
			{
				return this._MaPhanHoc;
			}
			set
			{
				if ((this._MaPhanHoc != value))
				{
					this.OnMaPhanHocChanging(value);
					this.SendPropertyChanging();
					this._MaPhanHoc = value;
					this.SendPropertyChanged("MaPhanHoc");
					this.OnMaPhanHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenPhanHoc", DbType="NVarChar(250)")]
		public string TenPhanHoc
		{
			get
			{
				return this._TenPhanHoc;
			}
			set
			{
				if ((this._TenPhanHoc != value))
				{
					this.OnTenPhanHocChanging(value);
					this.SendPropertyChanging();
					this._TenPhanHoc = value;
					this.SendPropertyChanged("TenPhanHoc");
					this.OnTenPhanHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="Int")]
		public System.Nullable<int> MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					if (this._KHOAHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANHOC_BAIHOC", Storage="_BAIHOCs", ThisKey="MaPhanHoc", OtherKey="MaPhanHoc")]
		public EntitySet<BAIHOC> BAIHOCs
		{
			get
			{
				return this._BAIHOCs;
			}
			set
			{
				this._BAIHOCs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHANHOC_CAUHOI", Storage="_CAUHOIs", ThisKey="MaPhanHoc", OtherKey="MaPhanHoc")]
		public EntitySet<CAUHOI> CAUHOIs
		{
			get
			{
				return this._CAUHOIs;
			}
			set
			{
				this._CAUHOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOAHOC_PHANHOC", Storage="_KHOAHOC", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc", IsForeignKey=true)]
		public KHOAHOC KHOAHOC
		{
			get
			{
				return this._KHOAHOC.Entity;
			}
			set
			{
				KHOAHOC previousValue = this._KHOAHOC.Entity;
				if (((previousValue != value) 
							|| (this._KHOAHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOAHOC.Entity = null;
						previousValue.PHANHOCs.Remove(this);
					}
					this._KHOAHOC.Entity = value;
					if ((value != null))
					{
						value.PHANHOCs.Add(this);
						this._MaKhoaHoc = value.MaKhoaHoc;
					}
					else
					{
						this._MaKhoaHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHOAHOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAIHOCs(BAIHOC entity)
		{
			this.SendPropertyChanging();
			entity.PHANHOC = this;
		}
		
		private void detach_BAIHOCs(BAIHOC entity)
		{
			this.SendPropertyChanging();
			entity.PHANHOC = null;
		}
		
		private void attach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.PHANHOC = this;
		}
		
		private void detach_CAUHOIs(CAUHOI entity)
		{
			this.SendPropertyChanging();
			entity.PHANHOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHANHOI")]
	public partial class PHANHOI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaPhanHoi;
		
		private System.Nullable<int> _MaKhoaHoc;
		
		private string _NoiDungPhanHoi;
		
		private System.Nullable<int> _MaThanhVien;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private System.Nullable<bool> _TrangThai;
		
		private EntityRef<KHOAHOC> _KHOAHOC;
		
		private EntityRef<THANHVIEN> _THANHVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaPhanHoiChanging(int value);
    partial void OnMaPhanHoiChanged();
    partial void OnMaKhoaHocChanging(System.Nullable<int> value);
    partial void OnMaKhoaHocChanged();
    partial void OnNoiDungPhanHoiChanging(string value);
    partial void OnNoiDungPhanHoiChanged();
    partial void OnMaThanhVienChanging(System.Nullable<int> value);
    partial void OnMaThanhVienChanged();
    partial void OnNgayDangChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDangChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    #endregion
		
		public PHANHOI()
		{
			this._KHOAHOC = default(EntityRef<KHOAHOC>);
			this._THANHVIEN = default(EntityRef<THANHVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaPhanHoi", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaPhanHoi
		{
			get
			{
				return this._MaPhanHoi;
			}
			set
			{
				if ((this._MaPhanHoi != value))
				{
					this.OnMaPhanHoiChanging(value);
					this.SendPropertyChanging();
					this._MaPhanHoi = value;
					this.SendPropertyChanged("MaPhanHoi");
					this.OnMaPhanHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="Int")]
		public System.Nullable<int> MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					if (this._KHOAHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungPhanHoi", DbType="NVarChar(500)")]
		public string NoiDungPhanHoi
		{
			get
			{
				return this._NoiDungPhanHoi;
			}
			set
			{
				if ((this._NoiDungPhanHoi != value))
				{
					this.OnNoiDungPhanHoiChanging(value);
					this.SendPropertyChanging();
					this._NoiDungPhanHoi = value;
					this.SendPropertyChanged("NoiDungPhanHoi");
					this.OnNoiDungPhanHoiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="Int")]
		public System.Nullable<int> MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					if (this._THANHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this.OnNgayDangChanging(value);
					this.SendPropertyChanging();
					this._NgayDang = value;
					this.SendPropertyChanged("NgayDang");
					this.OnNgayDangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOAHOC_PHANHOI", Storage="_KHOAHOC", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc", IsForeignKey=true)]
		public KHOAHOC KHOAHOC
		{
			get
			{
				return this._KHOAHOC.Entity;
			}
			set
			{
				KHOAHOC previousValue = this._KHOAHOC.Entity;
				if (((previousValue != value) 
							|| (this._KHOAHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOAHOC.Entity = null;
						previousValue.PHANHOIs.Remove(this);
					}
					this._KHOAHOC.Entity = value;
					if ((value != null))
					{
						value.PHANHOIs.Add(this);
						this._MaKhoaHoc = value.MaKhoaHoc;
					}
					else
					{
						this._MaKhoaHoc = default(Nullable<int>);
					}
					this.SendPropertyChanged("KHOAHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHVIEN_PHANHOI", Storage="_THANHVIEN", ThisKey="MaThanhVien", OtherKey="MaThanhVien", IsForeignKey=true)]
		public THANHVIEN THANHVIEN
		{
			get
			{
				return this._THANHVIEN.Entity;
			}
			set
			{
				THANHVIEN previousValue = this._THANHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHVIEN.Entity = null;
						previousValue.PHANHOIs.Remove(this);
					}
					this._THANHVIEN.Entity = value;
					if ((value != null))
					{
						value.PHANHOIs.Add(this);
						this._MaThanhVien = value.MaThanhVien;
					}
					else
					{
						this._MaThanhVien = default(Nullable<int>);
					}
					this.SendPropertyChanged("THANHVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHVIEN")]
	public partial class THANHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThanhVien;
		
		private string _TenThanhVien;
		
		private string _MatKhau;
		
		private string _Email;
		
		private System.Nullable<bool> _TrangThai;
		
		private string _GhiChu;
		
		private EntitySet<PHANHOI> _PHANHOIs;
		
		private EntitySet<THANHVIEN_KHOAHOC> _THANHVIEN_KHOAHOCs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhVienChanging(int value);
    partial void OnMaThanhVienChanged();
    partial void OnTenThanhVienChanging(string value);
    partial void OnTenThanhVienChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnTrangThaiChanging(System.Nullable<bool> value);
    partial void OnTrangThaiChanged();
    partial void OnGhiChuChanging(string value);
    partial void OnGhiChuChanged();
    #endregion
		
		public THANHVIEN()
		{
			this._PHANHOIs = new EntitySet<PHANHOI>(new Action<PHANHOI>(this.attach_PHANHOIs), new Action<PHANHOI>(this.detach_PHANHOIs));
			this._THANHVIEN_KHOAHOCs = new EntitySet<THANHVIEN_KHOAHOC>(new Action<THANHVIEN_KHOAHOC>(this.attach_THANHVIEN_KHOAHOCs), new Action<THANHVIEN_KHOAHOC>(this.detach_THANHVIEN_KHOAHOCs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenThanhVien", DbType="NVarChar(250)")]
		public string TenThanhVien
		{
			get
			{
				return this._TenThanhVien;
			}
			set
			{
				if ((this._TenThanhVien != value))
				{
					this.OnTenThanhVienChanging(value);
					this.SendPropertyChanging();
					this._TenThanhVien = value;
					this.SendPropertyChanged("TenThanhVien");
					this.OnTenThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="Char(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="Char(50) NOT NULL", CanBeNull=false)]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThai", DbType="Bit")]
		public System.Nullable<bool> TrangThai
		{
			get
			{
				return this._TrangThai;
			}
			set
			{
				if ((this._TrangThai != value))
				{
					this.OnTrangThaiChanging(value);
					this.SendPropertyChanging();
					this._TrangThai = value;
					this.SendPropertyChanged("TrangThai");
					this.OnTrangThaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GhiChu", DbType="NVarChar(250)")]
		public string GhiChu
		{
			get
			{
				return this._GhiChu;
			}
			set
			{
				if ((this._GhiChu != value))
				{
					this.OnGhiChuChanging(value);
					this.SendPropertyChanging();
					this._GhiChu = value;
					this.SendPropertyChanged("GhiChu");
					this.OnGhiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHVIEN_PHANHOI", Storage="_PHANHOIs", ThisKey="MaThanhVien", OtherKey="MaThanhVien")]
		public EntitySet<PHANHOI> PHANHOIs
		{
			get
			{
				return this._PHANHOIs;
			}
			set
			{
				this._PHANHOIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHVIEN_THANHVIEN_KHOAHOC", Storage="_THANHVIEN_KHOAHOCs", ThisKey="MaThanhVien", OtherKey="MaThanhVien")]
		public EntitySet<THANHVIEN_KHOAHOC> THANHVIEN_KHOAHOCs
		{
			get
			{
				return this._THANHVIEN_KHOAHOCs;
			}
			set
			{
				this._THANHVIEN_KHOAHOCs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHANHOIs(PHANHOI entity)
		{
			this.SendPropertyChanging();
			entity.THANHVIEN = this;
		}
		
		private void detach_PHANHOIs(PHANHOI entity)
		{
			this.SendPropertyChanging();
			entity.THANHVIEN = null;
		}
		
		private void attach_THANHVIEN_KHOAHOCs(THANHVIEN_KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.THANHVIEN = this;
		}
		
		private void detach_THANHVIEN_KHOAHOCs(THANHVIEN_KHOAHOC entity)
		{
			this.SendPropertyChanging();
			entity.THANHVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHVIEN_KHOAHOC")]
	public partial class THANHVIEN_KHOAHOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MaThanhVien;
		
		private int _MaKhoaHoc;
		
		private string _Loai;
		
		private System.Nullable<bool> _TrangThaiThanhToan;
		
		private EntityRef<KHOAHOC> _KHOAHOC;
		
		private EntityRef<THANHVIEN> _THANHVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaThanhVienChanging(int value);
    partial void OnMaThanhVienChanged();
    partial void OnMaKhoaHocChanging(int value);
    partial void OnMaKhoaHocChanged();
    partial void OnLoaiChanging(string value);
    partial void OnLoaiChanged();
    partial void OnTrangThaiThanhToanChanging(System.Nullable<bool> value);
    partial void OnTrangThaiThanhToanChanged();
    #endregion
		
		public THANHVIEN_KHOAHOC()
		{
			this._KHOAHOC = default(EntityRef<KHOAHOC>);
			this._THANHVIEN = default(EntityRef<THANHVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaThanhVien", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaThanhVien
		{
			get
			{
				return this._MaThanhVien;
			}
			set
			{
				if ((this._MaThanhVien != value))
				{
					if (this._THANHVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaThanhVienChanging(value);
					this.SendPropertyChanging();
					this._MaThanhVien = value;
					this.SendPropertyChanged("MaThanhVien");
					this.OnMaThanhVienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKhoaHoc", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int MaKhoaHoc
		{
			get
			{
				return this._MaKhoaHoc;
			}
			set
			{
				if ((this._MaKhoaHoc != value))
				{
					if (this._KHOAHOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKhoaHocChanging(value);
					this.SendPropertyChanging();
					this._MaKhoaHoc = value;
					this.SendPropertyChanged("MaKhoaHoc");
					this.OnMaKhoaHocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Loai", DbType="Char(50)")]
		public string Loai
		{
			get
			{
				return this._Loai;
			}
			set
			{
				if ((this._Loai != value))
				{
					this.OnLoaiChanging(value);
					this.SendPropertyChanging();
					this._Loai = value;
					this.SendPropertyChanged("Loai");
					this.OnLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TrangThaiThanhToan", DbType="Bit")]
		public System.Nullable<bool> TrangThaiThanhToan
		{
			get
			{
				return this._TrangThaiThanhToan;
			}
			set
			{
				if ((this._TrangThaiThanhToan != value))
				{
					this.OnTrangThaiThanhToanChanging(value);
					this.SendPropertyChanging();
					this._TrangThaiThanhToan = value;
					this.SendPropertyChanged("TrangThaiThanhToan");
					this.OnTrangThaiThanhToanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHOAHOC_THANHVIEN_KHOAHOC", Storage="_KHOAHOC", ThisKey="MaKhoaHoc", OtherKey="MaKhoaHoc", IsForeignKey=true)]
		public KHOAHOC KHOAHOC
		{
			get
			{
				return this._KHOAHOC.Entity;
			}
			set
			{
				KHOAHOC previousValue = this._KHOAHOC.Entity;
				if (((previousValue != value) 
							|| (this._KHOAHOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHOAHOC.Entity = null;
						previousValue.THANHVIEN_KHOAHOCs.Remove(this);
					}
					this._KHOAHOC.Entity = value;
					if ((value != null))
					{
						value.THANHVIEN_KHOAHOCs.Add(this);
						this._MaKhoaHoc = value.MaKhoaHoc;
					}
					else
					{
						this._MaKhoaHoc = default(int);
					}
					this.SendPropertyChanged("KHOAHOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THANHVIEN_THANHVIEN_KHOAHOC", Storage="_THANHVIEN", ThisKey="MaThanhVien", OtherKey="MaThanhVien", IsForeignKey=true)]
		public THANHVIEN THANHVIEN
		{
			get
			{
				return this._THANHVIEN.Entity;
			}
			set
			{
				THANHVIEN previousValue = this._THANHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHVIEN.Entity = null;
						previousValue.THANHVIEN_KHOAHOCs.Remove(this);
					}
					this._THANHVIEN.Entity = value;
					if ((value != null))
					{
						value.THANHVIEN_KHOAHOCs.Add(this);
						this._MaThanhVien = value.MaThanhVien;
					}
					else
					{
						this._MaThanhVien = default(int);
					}
					this.SendPropertyChanged("THANHVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
